name: TechTrends - Package with Docker

on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
    
jobs:
  build:
  
  
  
    runs-on: ubuntu-latest
    
    
    
steps: 
    name: Checkout code
    uses: actions/checkout@v2
    name: publish to GitHub packages
    uses: docker/build-push-action@v1
    with:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      registry: docker.pkg.github.com 
      repository: ${{ github.repository }}/next
      tags: techtrends:latest
